apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: "{{ crw_name }}"
  namespace: "{{ proj_nm_infra }}"
spec:
  server:
    cheFlavor: codeready
    tlsSupport: true
    selfSignedCert: false
		workspaceNamespaceDefault: "workspace-<username>-<workspaceid>"
    customCheProperties:
      # CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "2048"
      # CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "{{ crw_workspaces_namespace }}"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "9000000"
      CHE_WORKSPACE_JAVA__OPTIONS: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms512m -Djava.security.egd=file:/dev/./urandom"
      CHE_WORKSPACE_MAVEN__OPTIONS: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms512m -Djava.security.egd=file:/dev/./urandom"
  database:
    externalDB: false
  auth:
    openShiftoAuth: true
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
# ---
# apiVersion: console.openshift.io/v1
# kind: ConsoleLink
# metadata:
#   name: codeready-workspaces-app-menu-link
# spec:
#   href: "https://{{ crw_name }}-{{ proj_nm_infra }}.{{ cluster_wildcard_domain.resources[0].status.domain }}"
#   location: ApplicationMenu
#   text: CodeReady Workspaces
#   applicationMenu:
#     section: Development Tools
#     imageURL: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/product/branding/CodeReady.png
